### ISSUE TITLE
Problems with tt_videos(example_urls, save_video = TRUE)

### ISSUE THREAD

**Issue by ciaract** [JBGruber/traktok#10]
Hello, 

first of all: thank you very much for your work! It's great to have a package for Tiktok in R! 

Then a (maybe a bit trivial) question: I want to download the metadata of some videos. Unfortunately, every time I run the line `tt_videos(example_urls, save_video = TRUE)` I get the following error message: 
```
Error in `purrr::map()`:61216015648
ℹ In index: 1.
Caused by error in `save_tiktok()`:
! Retrieving data failed with message:
Error in httr2::req_perform(req) : Failed to perform HTTP request. Caused by error in `curl::curl_fetch_memory()`: ! Empty reply from
server
```
How can I solve this problem? 
Thank you in advance!

**Comment by JBGruber** [comment]
The main branch is currently somewhat broken. I will clean up and push an update I've been working on in another branch, hopefully later today. Sorry for the inconvenience.

**Comment by ciaract** [comment]
That sounds great thank you! Can you hit me up, when you have managed to fix the problem?

**Comment by JBGruber** [comment]
You can use the new version now (:partying_face: ). First install `cookiemonster` (where I moved the authentication part to) and `traktok` from Github:

```
remotes::install_github("JBGruber/cookiemonster")
remotes::install_github("JBGruber/traktok")
```

Add your cookies to the cookie jar:

```r
cookiemonster::add_cookies("cookies.txt")
```

Get videos:

```r
tt_videos(example_urls) # the new default is to download video files, so save_video = TRUE can be omitted
```

Would be great if you could tell me if that works for you :smiley:

**Comment by ciaract** [comment]
Sorry for my late reply. 
Unfortunately I am still getting (exactly the same) error.

**Comment by ciaract** [comment]
In general. 
I am wondering if I have saved the cookies incorrectly. But I actually used exactly the instructions you had in your readme last week.

**Comment by JBGruber** [comment]
Even without any cookies at all, I can't reproduce your error:

``` r
cookiemonster::delete_cookies("tiktok", ask = FALSE)
#> # A tibble: 0 × 2
#> # ℹ 2 variables: domain <chr>, name <chr>
#> ✔ Cookies deleted.
traktok::tt_videos("https://www.tiktok.com/@tiktok/video/7106594312292453675", max_tries = 1L)
#> ℹ Getting video 7106594312292453675
#> ! Download failed, retrying after 10 seconds. 1 left.
#> ℹ Getting video 7106594312292453675
#> Warning: Video 7106594312292453675 has a very small file size (less than 1kB) and is
#> likely corrupt.
#> ✔ Got video 7106594312292453675 (1/1).  [10.7s]
#> # A tibble: 1 × 19
#>   video_id            video_url     video_timestamp     video_length video_title
#>   <chr>               <chr>         <dttm>                     <int> <chr>      
#> 1 7106594312292453675 https://www.… 2022-06-07 20:15:29           24 how many f…
#> # ℹ 14 more variables: video_locationcreated <chr>, video_diggcount <int>,
#> #   video_sharecount <int>, video_commentcount <int>, video_playcount <int>,
#> #   author_username <chr>, author_nickname <chr>, author_bio <chr>,
#> #   download_url <chr>, html_status <int>, music <list>, challenges <list>,
#> #   is_classified <lgl>, video_fn <chr>
```

<sup>Created on 2023-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The video file can't be downloaded then, but I still get the metadata and the error is correctly handled. 

Can you please update `httr2` to the latest version and try again? If that doesn't help, could you post the video you are trying to access? And maybe sent me the last request and response (you can copy them to a file and send me an email if you prefer):

```
httr2::last_request() |> dput()
httr2::last_response() |> dput()
```

(This will only work after you use tt_videos)

**Comment by ciaract** [comment]
It still didn't work (I tried to download the metadata of the video you selected). I will send you an e-mail with the information about the last requests and response.

**Comment by JBGruber** [comment]
Thanks for sending the mail with your request. The problem is your cookies. I don't know what you did wrong, but my cookiejar has 32 values, yours has 2,877! It seems this overwhelms the server somehow.

Maybe all the cookies from your browser instead of just the ones for TikTok were included? That case should be handled by `cookiemonster`, but for some reason the domain selection didn't work, it seems. 

Did you use the recommended browser plugins to get the cookies just for tiktok? Note that I changed my recommendation for Chrome a while ago (if you still have the original "Get cookies.txt" you should [delete it immediatly](https://www.reddit.com/r/youtubedl/comments/10ar7o7/if_youve_been_using_the_get_cookiestxt_chrome/)). Maybe just try it again (after deleting the old cookies from your jar with `cookiemonster::delete_cookies("tiktok", ask = FALSE)`).

**Comment by JBGruber** [comment]
FYI, this is roughly what you should see when reaching into the cookiejar to get the TikTok cookies :wink::

```
> cookiemonster::get_cookies("tiktok.com")
# A tibble: 32 × 7
   domain    flag  path  secure expiration          name  value
   <chr>     <lgl> <chr> <lgl>  <dttm>              <chr> <chr>
 1 tiktok.c… TRUE  /     TRUE   2024-10-13 11:13:25 cook… {%22…
 2 tiktok.c… TRUE  /     TRUE   2023-11-20 10:16:28 pass… e07d…
 3 tiktok.c… TRUE  /     FALSE  2023-11-20 10:16:28 pass… e07d…
 4 tiktok.c… TRUE  /     TRUE   2023-11-20 16:20:10 mult… 7157…
 5 tiktok.c… TRUE  /     TRUE   2023-11-20 16:20:10 cmpl… AgQQ…
 6 tiktok.c… TRUE  /     TRUE   2024-09-20 17:20:10 ttwid 1%7C…
 7 tiktok.c… TRUE  /     TRUE   2024-09-15 17:20:10 sid_… 904e…
 8 tiktok.c… TRUE  /     TRUE   2024-03-19 16:20:10 uid_… a690…
 9 tiktok.c… TRUE  /     TRUE   2024-03-19 16:20:10 uid_… a690…
10 tiktok.c… TRUE  /     TRUE   2024-03-19 16:20:10 sid_… 904e…
# ℹ 22 more rows
# ℹ Use `print(n = ...)` to see more rows
```

**Comment by ciaract** [comment]
I'm just getting an overview of your messages at this very moment :) 

One more question, because it's not entirely clear to me from the documentation about the package:
Do you "only" load the cookies via cookiemonster::get_cookies("tiktok.com")

Or do you load the cookies beforehand via the browser extension (e.g. via Firefox, as you recommend here (https://github.com/JBGruber/cookiemonster), then save them with add_cookies() and then access them with "get_cookies()?

**Comment by JBGruber** [comment]
Fair question!

- `add_cookies()` puts cookies (retrieved from the browser through an extension or some other means) into a jar that `R` can access
- `get_cookies()` retrieves the cookies from said jar
- `delete_cookies()` removes previously stored cookies

So if you don't run `add_cookies() ` first, there will simply be nothing in the cookie jar. Internally, `traktok` uses the cookies from the jar by looking for all cookies for the domain "tiktok.com":

https://github.com/JBGruber/traktok/blob/1646d74c25419019fc8b4c3f6f4072674bc10af6/R/api_hidden.r#L53

The regular expression shouldn't usually be neccesary, it's there just in case.

Now from the request you sent me, it looks like your cookies were stored under a wrong domain name somehow. Instead of retrieving just the cookies for TikTok, all cookies loaded somehow (or that's what I assume, since there were so many).

**Comment by ciaract** [comment]
It worked! Thank you so much for your help and patience!

**Comment by JBGruber** [comment]
Fantastic! I hope you do some cool research with it. And let me know if anything else goes wrong.
